version: '3'
services:
  vue-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
    networks:
      - bridge-net

networks:
  bridge-net:
    driver: bridge
