version: '3'
services:
  vue-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    container_name: vue-ui
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
